#include <stddef.h>
#include "stm32l1xx.h"
#include "../common.h"

#include "lcd.h"

#define LCD_CS(segment) {LCD_C_(segment), LCD_S_(segment)}

CODE TLcdSeg lcdSeg[LCD_DIGIT_NR][LCD_SEG_NR] = {
  { LCD_CS(1A), LCD_CS(1B), LCD_CS(1C), LCD_CS(1D), LCD_CS(1E), LCD_CS(1F), LCD_CS(1G), LCD_CS(1H), LCD_CS(1J), LCD_CS(1K), LCD_CS(1M), LCD_CS(1N), LCD_CS(1P), LCD_CS(1Q), LCD_CS(1DP), LCD_CS(1COLON), },
  { LCD_CS(2A), LCD_CS(2B), LCD_CS(2C), LCD_CS(2D), LCD_CS(2E), LCD_CS(2F), LCD_CS(2G), LCD_CS(2H), LCD_CS(2J), LCD_CS(2K), LCD_CS(2M), LCD_CS(2N), LCD_CS(2P), LCD_CS(2Q), LCD_CS(2DP), LCD_CS(2COLON), },
  { LCD_CS(3A), LCD_CS(3B), LCD_CS(3C), LCD_CS(3D), LCD_CS(3E), LCD_CS(3F), LCD_CS(3G), LCD_CS(3H), LCD_CS(3J), LCD_CS(3K), LCD_CS(3M), LCD_CS(3N), LCD_CS(3P), LCD_CS(3Q), LCD_CS(3DP), LCD_CS(3COLON), },
  { LCD_CS(4A), LCD_CS(4B), LCD_CS(4C), LCD_CS(4D), LCD_CS(4E), LCD_CS(4F), LCD_CS(4G), LCD_CS(4H), LCD_CS(4J), LCD_CS(4K), LCD_CS(4M), LCD_CS(4N), LCD_CS(4P), LCD_CS(4Q), LCD_CS(4DP), LCD_CS(4COLON), },
  { LCD_CS(5A), LCD_CS(5B), LCD_CS(5C), LCD_CS(5D), LCD_CS(5E), LCD_CS(5F), LCD_CS(5G), LCD_CS(5H), LCD_CS(5J), LCD_CS(5K), LCD_CS(5M), LCD_CS(5N), LCD_CS(5P), LCD_CS(5Q), LCD_CS(5DP), LCD_CS(5COLON), },
  { LCD_CS(6A), LCD_CS(6B), LCD_CS(6C), LCD_CS(6D), LCD_CS(6E), LCD_CS(6F), LCD_CS(6G), LCD_CS(6H), LCD_CS(6J), LCD_CS(6K), LCD_CS(6M), LCD_CS(6N), LCD_CS(6P), LCD_CS(6Q), LCD_CS(6DP), LCD_CS(6COLON), },
};

CODE uint16_t lcdAlphaTab[26] = {
  0x0477, 0x150f, 0x0039, 0x110f, 0x0079, 0x0071, 0x043d, 0x0476, 0x1100, 0x001e,  // ABCDEFGHIJ
  0x0a70, 0x0038, 0x02b6, 0x08b6, 0x003f, 0x0473, 0x083f, 0x0c73, 0x046d, 0x1101,  // KLMNOPQRST
  0x003e, 0x2230, 0x2836, 0x2a80, 0x1280, 0x2209,                                  // UVWXYZ
};

CODE uint16_t lcdDigitTab[10] = {
  0x003f, 0x0006, 0x045b, 0x040f,  0x0466, 0x046d, 0x047d, 0x0007, 0x047f, 0x046f,
};

void LcdPrintChar(uint8_t digit, char c) {
  uint8_t i;
  uint16_t a;

  digit = digit % 6;
  if ((c >= '0') && (c <= '9')) a = lcdDigitTab[c - '0'];
  else if ((c >= 'a') && (c <= 'z')) a = lcdAlphaTab[c - 'a'];
  else if ((c >= 'A') && (c <= 'Z')) a = lcdAlphaTab[c - 'A'];
  else if (c == ' ') a = 0x0000;
  else a = 0x0440; // --
  for (i = 0; i < 14; i++) {
	  LCD_SEG(digit, i) = a & 1;
	  a = a >> 1;
  }
}

void LcdPrintString( uint8_t start, char * str){
	while(*str){
		LcdPrintChar(start, *str);
		str++;
		start+=1;
		start = start %6;
	}
}

void LcdPrintDot( uint8_t digit, T_Lcd_dots dots ){
	digit = digit % 6;
	if(digit >= 4) return;
	for(uint8_t i = 0; i<2; i++){
		LCD_SEG(digit, i+14) = dots & 1;
		dots = dots >>1;
	}
}

void LcdPrintBar( uint8_t val ){
	for(uint8_t i = 0; i<4; i++){
		LCD_SEG(5-(i/2) , (i%2)+14) = val & 1;
	 	val = val>>1;
	}
}

void LcdUpdate(){
	LCD->CLR |= (LCD_CLR_UDDC);
	LCD->SR |= (LCD_SR_UDR);
}

void LcdIoInit(){
	GPIOA->MODER |= (GPIO_MODER_MODER1_1)
	| (GPIO_MODER_MODER2_1)
	| (GPIO_MODER_MODER3_1)
	| (GPIO_MODER_MODER8_1)
	| (GPIO_MODER_MODER9_1)
	| (GPIO_MODER_MODER10_1)
	| (GPIO_MODER_MODER15_1);

	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR1_1)
	| (GPIO_OSPEEDER_OSPEEDR2_1)
	| (GPIO_OSPEEDER_OSPEEDR3_1)
	| (GPIO_OSPEEDER_OSPEEDR8_1)
	| (GPIO_OSPEEDER_OSPEEDR9_1)
	| (GPIO_OSPEEDER_OSPEEDR10_1)
	| (GPIO_OSPEEDER_OSPEEDR15_1);

	GPIOA->PUPDR &= ~((GPIO_PUPDR_PUPDR1_0) | (GPIO_PUPDR_PUPDR1_1)
	| (GPIO_PUPDR_PUPDR2_0) | (GPIO_PUPDR_PUPDR2_1)
	| (GPIO_PUPDR_PUPDR3_0) | (GPIO_PUPDR_PUPDR3_1)
	| (GPIO_PUPDR_PUPDR8_0) | (GPIO_PUPDR_PUPDR8_1)
	| (GPIO_PUPDR_PUPDR9_0) | (GPIO_PUPDR_PUPDR9_1)
	| (GPIO_PUPDR_PUPDR10_0) | (GPIO_PUPDR_PUPDR10_1)
	| (GPIO_PUPDR_PUPDR15_0) | (GPIO_PUPDR_PUPDR15_1));

	GPIOA->AFR[0] |= 0x0000BBB0;
	GPIOA->AFR[1] |= 0xB0000BBB;


	GPIOB->MODER |= (GPIO_MODER_MODER3_1)
	| (GPIO_MODER_MODER4_1)
	| (GPIO_MODER_MODER5_1)
	| (GPIO_MODER_MODER8_1)
	| (GPIO_MODER_MODER9_1)
	| (GPIO_MODER_MODER10_1)
	| (GPIO_MODER_MODER11_1)
	| (GPIO_MODER_MODER12_1)
	| (GPIO_MODER_MODER13_1)
	| (GPIO_MODER_MODER14_1)
	| (GPIO_MODER_MODER15_1);

	GPIOB->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR3_1)
	| (GPIO_OSPEEDER_OSPEEDR4_1)
	| (GPIO_OSPEEDER_OSPEEDR5_1)
	| (GPIO_OSPEEDER_OSPEEDR8_1)
	| (GPIO_OSPEEDER_OSPEEDR9_1)
	| (GPIO_OSPEEDER_OSPEEDR10_1)
	| (GPIO_OSPEEDER_OSPEEDR11_1)
	| (GPIO_OSPEEDER_OSPEEDR12_1)
	| (GPIO_OSPEEDER_OSPEEDR13_1)
	| (GPIO_OSPEEDER_OSPEEDR14_1)
	| (GPIO_OSPEEDER_OSPEEDR15_1);

	GPIOB->PUPDR &= ~((GPIO_PUPDR_PUPDR3_0) | (GPIO_PUPDR_PUPDR3_1)
	| (GPIO_PUPDR_PUPDR4_0) | (GPIO_PUPDR_PUPDR4_1)
	| (GPIO_PUPDR_PUPDR5_0) | (GPIO_PUPDR_PUPDR5_1)
	| (GPIO_PUPDR_PUPDR8_0) | (GPIO_PUPDR_PUPDR8_1)
	| (GPIO_PUPDR_PUPDR9_0) | (GPIO_PUPDR_PUPDR9_1)
	| (GPIO_PUPDR_PUPDR10_0) | (GPIO_PUPDR_PUPDR10_1)
	| (GPIO_PUPDR_PUPDR11_0) | (GPIO_PUPDR_PUPDR11_1)
	| (GPIO_PUPDR_PUPDR12_0) | (GPIO_PUPDR_PUPDR12_1)
	| (GPIO_PUPDR_PUPDR13_0) | (GPIO_PUPDR_PUPDR13_1)
	| (GPIO_PUPDR_PUPDR14_0) | (GPIO_PUPDR_PUPDR14_1)
	| (GPIO_PUPDR_PUPDR15_0) | (GPIO_PUPDR_PUPDR15_1));

	GPIOB->AFR[0] |= 0x00BBB000;
	GPIOB->AFR[1] |= 0xBBBBBBBB;


	GPIOC->MODER |= (GPIO_MODER_MODER0_1)
	| (GPIO_MODER_MODER1_1)
	| (GPIO_MODER_MODER2_1)
	| (GPIO_MODER_MODER3_1)
	| (GPIO_MODER_MODER6_1)
	| (GPIO_MODER_MODER7_1)
	| (GPIO_MODER_MODER8_1)
	| (GPIO_MODER_MODER9_1)
	| (GPIO_MODER_MODER10_1)
	| (GPIO_MODER_MODER11_1);

	GPIOC->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR0_1)
	| (GPIO_OSPEEDER_OSPEEDR1_1)
	| (GPIO_OSPEEDER_OSPEEDR2_1)
	| (GPIO_OSPEEDER_OSPEEDR3_1)
	| (GPIO_OSPEEDER_OSPEEDR6_1)
	| (GPIO_OSPEEDER_OSPEEDR7_1)
	| (GPIO_OSPEEDER_OSPEEDR8_1)
	| (GPIO_OSPEEDER_OSPEEDR9_1)
	| (GPIO_OSPEEDER_OSPEEDR10_1)
	| (GPIO_OSPEEDER_OSPEEDR11_1);

	GPIOC->PUPDR &= ~((GPIO_PUPDR_PUPDR0_0) | (GPIO_PUPDR_PUPDR0_1)
	| (GPIO_PUPDR_PUPDR1_0) | (GPIO_PUPDR_PUPDR1_1)
	| (GPIO_PUPDR_PUPDR2_0) | (GPIO_PUPDR_PUPDR2_1)
	| (GPIO_PUPDR_PUPDR3_0) | (GPIO_PUPDR_PUPDR3_1)
	| (GPIO_PUPDR_PUPDR6_0) | (GPIO_PUPDR_PUPDR6_1)
	| (GPIO_PUPDR_PUPDR7_0) | (GPIO_PUPDR_PUPDR7_1)
	| (GPIO_PUPDR_PUPDR8_0) | (GPIO_PUPDR_PUPDR8_1)
	| (GPIO_PUPDR_PUPDR9_0) | (GPIO_PUPDR_PUPDR9_1)
	| (GPIO_PUPDR_PUPDR10_0) | (GPIO_PUPDR_PUPDR10_1)
	| (GPIO_PUPDR_PUPDR11_0) | (GPIO_PUPDR_PUPDR11_1));

	GPIOC->AFR[0] |= 0xBB00BBBB;
	GPIOC->AFR[1] |= 0x0000BBBB;

}
